pplication:
    build: src
    volumes:
        - /var/www/symfony:/var/www/symfony
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    volumes:
        - /var/lib/mysql:/var/lib/mysql
        - /var/log/mysql:/var/log/mysql
php:
    build: php-fpm
    expose:
        - 9000/http
    volumes_from:
        - application
    links:
        - db
nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - /var/log/nginx:/var/log/nginx
